[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
gas_reports = ["FundraisingFactory", "FundraisingCampaign"]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[profile.test]
verbosity = 3
gas_reports = ["*"]